### ISSUE TITLE
Firing on Play/Pause after hitting Skip Intro

### ISSUE THREAD

**Issue by alex-seosavvy** [noahkiss/netflix-skip-intro#1]
Works great except after it presses "Skip Intro" it keeps firing on the Play/Pause button causing a stuttering effect. Maybe it has something to do with the "Skip Intro" button animation?

**Comment by g3n35i5** [comment]
I'm currently working on a patch that allows the button to be pressed and then a protection interval of 10 seconds is maintained so that the Netflix button can disappear. I'm about to make a pull request.
